create table public.logo_assets (
  id bigint generated by default as identity primary key,
  nama_aset text not null,
  slug text not null unique,
  kategori_aset text,
  jenis_lisensi text,
  svg_content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies (adjust as needed, currently allowing public read)
alter table public.logo_assets enable row level security;

create policy "Enable read access for all users"
on public.logo_assets for select
using (true);

create policy "Enable insert for authenticated users only"
on public.logo_assets for insert
with check (auth.role() = 'authenticated');

create policy "Enable update for authenticated users only"
on public.logo_assets for update
using (auth.role() = 'authenticated');

create policy "Enable delete for authenticated users only"
on public.logo_assets for delete
using (auth.role() = 'authenticated');
